### ISSUE TITLE
Numbering of sections in modular html

### ISSUE THREAD

**Issue by fbenke-pik** [pik-piam/goxygen#23]
![image](https://github.com/pik-piam/goxygen/assets/69258269/1196d849-2dcb-45a2-bae9-4eb70f47d21c)

The numbering in the navigation for modular HTML currently follows this logic:

`If all names except two begin with a number, use that number in front of the title.`
(probably a rule created with index page and core page in mind)
Source https://github.com/pik-piam/goxygen/blob/master/R/buildHTML.R#L84

Can we come up with a more straightforward rule? On REMIND side (@LaviniaBaumstark), we would be cool with either making it a parameter that can be passed (e.g. `numberedTitles = TRUE/FALSE`) or always using the number. What do you think @tscheypidi ?

**Comment by tscheypidi** [comment]
To me it looks like it should be ok to always use the number if available. I am not sure why it is currently formulated as an if-clause.

**Comment by fbenke-pik** [comment]
Ok, if that works for you, I'll prepare a PR
