### ISSUE TITLE
How is the core documented?

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/goxygen#3]
Documentation lines from the files in `./core/` don't show up anywhere in the documentation output or intermediate files.
```
$ grep -lr "Fuel costs are" *
core/equations.gms
```
whereas those from module files do
```
$ grep -lr "The macro module" *
doc/markdown/01_macro.md
doc/html/01_macro.htm
doc/documentation.tex
modules/01_macro/module.gms
```
Is this by design and there is to be no meaningful code in the core, just the modules?  Or will documentation be extended to cover the `./core/` directory?

**Comment by tscheypidi** [comment]
you can include the core via `includeCore = FALSE`
